'use client';

import { ReactNode, useEffect, useState } from 'react';
import Image from 'next/image';
import { ArrowLeft, ArrowRight, Check, Eye, EyeOff } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { Badge } from '@/atoms/Badge/Badge';
import { Button } from '@/atoms/Button/Button';
import { Container } from '@/atoms/Container/Container';
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/atoms/Dialog/Dialog';
import { useRecoveryPhraseValidation } from '@/hooks/useRecoveryPhraseValidation/useRecoveryPhraseValidation';
import { cn } from '@/libs/utils/utils';
import { WordSlot } from '@/molecules/WordSlot/WordSlot';
import { useOnboardingStore } from '@/stores/onboarding/onboarding.store';

interface DialogBackupPhraseProps {
  children?: ReactNode;
}
export function DialogBackupPhrase({ children }: DialogBackupPhraseProps) {
  const [isHidden, setIsHidden] = useState(true);
  const [recoveryWords, setRecoveryWords] = useState<string[]>([]);
  const [step, setStep] = useState(1);
  const { mnemonic } = useOnboardingStore();
  const t = useTranslations('onboarding.backupPhrase');
  const tCommon = useTranslations('common');
  const handleClose = () => {
    setIsHidden(true);
    setStep(1);
  };
  useEffect(() => {
    if (mnemonic) {
      // Use existing mnemonic (generated by PublicKeyCard)
      setRecoveryWords(mnemonic.split(' '));
    }
  }, [mnemonic]);
  return (
    <Dialog
      onOpenChange={(open) => {
        if (!open) {
          handleClose();
        }
      }}
    >
      {children ? (
        <DialogTrigger asChild>{children}</DialogTrigger>
      ) : (
        <DialogTrigger asChild>
          <Button id="backup-recovery-phrase-btn">{tCommon('continue')}</Button>
        </DialogTrigger>
      )}
      <DialogContent className="max-w-sm md:max-w-2xl" hiddenTitle={t('title')}>
        {step === 1 && (
          <RecoveryStep1
            recoveryWords={recoveryWords}
            isHidden={isHidden}
            setIsHidden={setIsHidden}
            setStep={setStep}
          />
        )}
        {step === 2 && <RecoveryStep2 recoveryWords={recoveryWords} setStep={setStep} />}
        {step === 3 && <RecoveryStep3 handleClose={handleClose} />}
      </DialogContent>
    </Dialog>
  );
}
function RecoveryStep1({
  recoveryWords,
  isHidden,
  setIsHidden,
  setStep,
}: {
  recoveryWords: string[];
  isHidden: boolean;
  setIsHidden: (isHidden: boolean) => void;
  setStep: (step: number) => void;
}) {
  const t = useTranslations('onboarding.backupPhrase');
  const tCommon = useTranslations('common');
  return (
    <>
      <DialogHeader>
        <DialogTitle>{t('title')}</DialogTitle>
        <DialogDescription>
          <span className="hidden md:inline">{t('subtitle')} </span>
          <span className="md:hidden">{t('writeDown')} </span>
          <span className="font-bold text-brand">{t('neverShare')}</span>
        </DialogDescription>
      </DialogHeader>

      <Container className={cn(isHidden && 'blur-md')}>
        <Container display="grid" className="grid-cols-2 gap-1.5 md:grid-cols-3 md:gap-3">
          {recoveryWords.map((word, index) => (
            <Container
              key={index}
              className="flex-row items-center gap-2 rounded-md bg-secondary px-3 py-3 sm:gap-3 sm:px-5 sm:py-4"
            >
              <Badge
                id={`backup-recovery-phrase-word-${index + 1}`}
                variant="outline"
                className="h-5 min-w-[20px] shrink-0 rounded-full px-1 font-semibold"
              >
                {index + 1}
              </Badge>
              <span className="text-sm font-medium sm:text-base">{word}</span>
            </Container>
          ))}
        </Container>
      </Container>

      <DialogFooter>
        {isHidden ? (
          <>
            <DialogClose asChild>
              <Button id="backup-recovery-phrase-cancel-btn" variant="outline" size="lg">
                {tCommon('cancel')}
              </Button>
            </DialogClose>
            <Button
              id="backup-recovery-phrase-reveal-btn"
              size="lg"
              onClick={() => {
                setIsHidden(!isHidden);
                setStep(1);
              }}
            >
              <Eye className="h-4 w-4" />
              {t('reveal')}
            </Button>
          </>
        ) : (
          <>
            <div className="contents md:hidden">
              <Button id="backup-recovery-phrase-confirm-btn-mobile" size="lg" onClick={() => setStep(2)}>
                <ArrowRight className="h-4 w-4" />
                {t('confirmTitle')}
              </Button>
              <Button
                variant="outline"
                size="lg"
                onClick={() => {
                  setIsHidden(!isHidden);
                  setStep(1);
                }}
              >
                <EyeOff className="h-4 w-4" />
                {t('hide')}
              </Button>
            </div>
            <div className="hidden md:contents">
              <Button
                variant="outline"
                size="lg"
                onClick={() => {
                  setIsHidden(!isHidden);
                  setStep(1);
                }}
              >
                <EyeOff className="h-4 w-4" />
                {t('hide')}
              </Button>
              <Button id="backup-recovery-phrase-confirm-btn-desktop" size="lg" onClick={() => setStep(2)}>
                <ArrowRight className="h-4 w-4" />
                {t('confirmTitle')}
              </Button>
            </div>
          </>
        )}
      </DialogFooter>
    </>
  );
}
function RecoveryStep2({ recoveryWords, setStep }: { recoveryWords: string[]; setStep: (step: number) => void }) {
  const { userWords, errors, remainingWords, handleWordClick, validateWords, clearWord, isComplete } =
    useRecoveryPhraseValidation({
      recoveryWords,
    });
  const t = useTranslations('onboarding.backupPhrase');
  const tCommon = useTranslations('common');
  const handleValidate = () => {
    if (validateWords()) {
      setStep(3);
    }
  };
  return (
    <>
      <DialogHeader>
        <DialogTitle>{t('confirmTitle')}</DialogTitle>
        <DialogDescription>{t('confirmSubtitle')}</DialogDescription>
      </DialogHeader>

      <Container className="space-y-6">
        <Container className="flex-row flex-wrap gap-2">
          {remainingWords.map(({ word, index, isUsed }) => (
            <Button
              id={`backup-recovery-phrase-word-${word}-${index + 1}`}
              key={`${word}-${index}`}
              variant={isUsed ? 'secondary' : 'outline'}
              className={`rounded-full ${isUsed ? 'cursor-not-allowed border bg-transparent text-muted-foreground opacity-40' : 'cursor-pointer border-transparent bg-secondary'}`}
              onClick={() => !isUsed && handleWordClick(word)}
              disabled={isUsed}
            >
              {word}
            </Button>
          ))}
        </Container>

        <Container display="grid" className="grid-cols-2 gap-1.5 sm:grid-cols-3 md:gap-3">
          {userWords.map((word, i) => {
            const isCorrect = word !== '' && word === recoveryWords[i];
            const isError = errors[i];
            return (
              <WordSlot
                key={i}
                mode="readonly"
                index={i}
                word={word}
                isCorrect={isCorrect}
                isError={isError}
                onClear={clearWord}
              />
            );
          })}
        </Container>
      </Container>

      <DialogFooter>
        <Button variant="outline" size="lg" onClick={() => setStep(1)}>
          <ArrowLeft className="h-4 w-4" />
          {tCommon('back')}
        </Button>
        <Button id="backup-recovery-phrase-validate-btn" size="lg" onClick={handleValidate} disabled={!isComplete}>
          <Check className="h-4 w-4" />
          {t('validate')}
        </Button>
      </DialogFooter>
    </>
  );
}
function RecoveryStep3({ handleClose }: { handleClose: () => void }) {
  const t = useTranslations('onboarding.backupPhrase');
  const tCommon = useTranslations('common');
  return (
    <>
      <DialogHeader>
        <DialogTitle>{t('completeTitle')}</DialogTitle>
        <DialogDescription>{t('completeSubtitle')}</DialogDescription>
      </DialogHeader>

      <Container className="flex w-full items-center justify-center rounded-md bg-card p-12">
        <Image src="/images/check.webp" alt={t('completeTitle')} width={180} height={180} className="h-48 w-48" />
      </Container>

      <DialogFooter className="flex-col gap-3">
        <DialogClose asChild>
          <Button id="backup-recovery-phrase-finish-btn" size="lg" className="w-full" onClick={handleClose}>
            <ArrowRight className="h-4 w-4" />
            {tCommon('finish')}
          </Button>
        </DialogClose>
        <DialogClose asChild>
          <Button variant="outline" size="lg" className="w-full" onClick={handleClose}>
            {tCommon('cancel')}
          </Button>
        </DialogClose>
      </DialogFooter>
    </>
  );
}
