'use client';

import { useState, useEffect, ReactNode } from 'react';
import Image from 'next/image';
import { useTranslations } from 'next-intl';

import * as Atoms from '@/components/atoms';
import * as Libs from '@/libs';
import * as Stores from '@/core';
import * as Molecules from '@/molecules';
import * as Hooks from '@/hooks';

interface DialogBackupPhraseProps {
  children?: ReactNode;
}

export function DialogBackupPhrase({ children }: DialogBackupPhraseProps) {
  const [isHidden, setIsHidden] = useState(true);
  const [recoveryWords, setRecoveryWords] = useState<string[]>([]);
  const [step, setStep] = useState(1);
  const { mnemonic } = Stores.useOnboardingStore();
  const t = useTranslations('onboarding.backupPhrase');
  const tCommon = useTranslations('common');

  const handleClose = () => {
    setIsHidden(true);
    setStep(1);
  };

  useEffect(() => {
    if (mnemonic) {
      // Use existing mnemonic (generated by PublicKeyCard)
      setRecoveryWords(mnemonic.split(' '));
    }
  }, [mnemonic]);

  return (
    <Atoms.Dialog
      onOpenChange={(open) => {
        if (!open) {
          handleClose();
        }
      }}
    >
      {children ? (
        <Atoms.DialogTrigger asChild>{children}</Atoms.DialogTrigger>
      ) : (
        <Atoms.DialogTrigger asChild>
          <Atoms.Button id="backup-recovery-phrase-btn">{tCommon('continue')}</Atoms.Button>
        </Atoms.DialogTrigger>
      )}
      <Atoms.DialogContent className="max-w-sm md:max-w-2xl" hiddenTitle={t('title')}>
        {step === 1 && (
          <RecoveryStep1
            recoveryWords={recoveryWords}
            isHidden={isHidden}
            setIsHidden={setIsHidden}
            setStep={setStep}
          />
        )}
        {step === 2 && <RecoveryStep2 recoveryWords={recoveryWords} setStep={setStep} />}
        {step === 3 && <RecoveryStep3 handleClose={handleClose} />}
      </Atoms.DialogContent>
    </Atoms.Dialog>
  );
}

function RecoveryStep1({
  recoveryWords,
  isHidden,
  setIsHidden,
  setStep,
}: {
  recoveryWords: string[];
  isHidden: boolean;
  setIsHidden: (isHidden: boolean) => void;
  setStep: (step: number) => void;
}) {
  const t = useTranslations('onboarding.backupPhrase');
  const tCommon = useTranslations('common');

  return (
    <>
      <Atoms.DialogHeader>
        <Atoms.DialogTitle>{t('title')}</Atoms.DialogTitle>
        <Atoms.DialogDescription>
          <span className="hidden md:inline">{t('subtitle')} </span>
          <span className="md:hidden">{t('writeDown')} </span>
          <span className="font-bold text-brand">{t('neverShare')}</span>
        </Atoms.DialogDescription>
      </Atoms.DialogHeader>

      <Atoms.Container className={Libs.cn(isHidden && 'blur-md')}>
        <Atoms.Container display="grid" className="grid-cols-2 gap-1.5 md:grid-cols-3 md:gap-3">
          {recoveryWords.map((word, index) => (
            <Atoms.Container
              key={index}
              className="flex-row items-center gap-2 rounded-md bg-secondary px-3 py-3 sm:gap-3 sm:px-5 sm:py-4"
            >
              <Atoms.Badge
                id={`backup-recovery-phrase-word-${index + 1}`}
                variant="outline"
                className="h-5 min-w-[20px] shrink-0 rounded-full px-1 font-semibold"
              >
                {index + 1}
              </Atoms.Badge>
              <span className="text-sm font-medium sm:text-base">{word}</span>
            </Atoms.Container>
          ))}
        </Atoms.Container>
      </Atoms.Container>

      <Atoms.DialogFooter>
        {isHidden ? (
          <>
            <Atoms.DialogClose asChild>
              <Atoms.Button id="backup-recovery-phrase-cancel-btn" variant="outline" size="lg">
                {tCommon('cancel')}
              </Atoms.Button>
            </Atoms.DialogClose>
            <Atoms.Button
              id="backup-recovery-phrase-reveal-btn"
              size="lg"
              onClick={() => {
                setIsHidden(!isHidden);
                setStep(1);
              }}
            >
              <Libs.Eye className="h-4 w-4" />
              {t('reveal')}
            </Atoms.Button>
          </>
        ) : (
          <>
            <div className="contents md:hidden">
              <Atoms.Button id="backup-recovery-phrase-confirm-btn-mobile" size="lg" onClick={() => setStep(2)}>
                <Libs.ArrowRight className="h-4 w-4" />
                {t('confirmTitle')}
              </Atoms.Button>
              <Atoms.Button
                variant="outline"
                size="lg"
                onClick={() => {
                  setIsHidden(!isHidden);
                  setStep(1);
                }}
              >
                <Libs.EyeOff className="h-4 w-4" />
                {t('hide')}
              </Atoms.Button>
            </div>
            <div className="hidden md:contents">
              <Atoms.Button
                variant="outline"
                size="lg"
                onClick={() => {
                  setIsHidden(!isHidden);
                  setStep(1);
                }}
              >
                <Libs.EyeOff className="h-4 w-4" />
                {t('hide')}
              </Atoms.Button>
              <Atoms.Button id="backup-recovery-phrase-confirm-btn-desktop" size="lg" onClick={() => setStep(2)}>
                <Libs.ArrowRight className="h-4 w-4" />
                {t('confirmTitle')}
              </Atoms.Button>
            </div>
          </>
        )}
      </Atoms.DialogFooter>
    </>
  );
}

function RecoveryStep2({ recoveryWords, setStep }: { recoveryWords: string[]; setStep: (step: number) => void }) {
  const { userWords, errors, remainingWords, handleWordClick, validateWords, clearWord, isComplete } =
    Hooks.useRecoveryPhraseValidation({ recoveryWords });
  const t = useTranslations('onboarding.backupPhrase');
  const tCommon = useTranslations('common');

  const handleValidate = () => {
    if (validateWords()) {
      setStep(3);
    }
  };

  return (
    <>
      <Atoms.DialogHeader>
        <Atoms.DialogTitle>{t('confirmTitle')}</Atoms.DialogTitle>
        <Atoms.DialogDescription>{t('confirmSubtitle')}</Atoms.DialogDescription>
      </Atoms.DialogHeader>

      <Atoms.Container className="space-y-6">
        <Atoms.Container className="flex-row flex-wrap gap-2">
          {remainingWords.map(({ word, index, isUsed }) => (
            <Atoms.Button
              id={`backup-recovery-phrase-word-${word}-${index + 1}`}
              key={`${word}-${index}`}
              variant={isUsed ? 'secondary' : 'outline'}
              className={`rounded-full ${
                isUsed
                  ? 'cursor-not-allowed border bg-transparent text-muted-foreground opacity-40'
                  : 'cursor-pointer border-transparent bg-secondary'
              }`}
              onClick={() => !isUsed && handleWordClick(word)}
              disabled={isUsed}
            >
              {word}
            </Atoms.Button>
          ))}
        </Atoms.Container>

        <Atoms.Container display="grid" className="grid-cols-2 gap-1.5 sm:grid-cols-3 md:gap-3">
          {userWords.map((word, i) => {
            const isCorrect = word !== '' && word === recoveryWords[i];
            const isError = errors[i];
            return (
              <Molecules.WordSlot
                key={i}
                mode="readonly"
                index={i}
                word={word}
                isCorrect={isCorrect}
                isError={isError}
                onClear={clearWord}
              />
            );
          })}
        </Atoms.Container>
      </Atoms.Container>

      <Atoms.DialogFooter>
        <Atoms.Button variant="outline" size="lg" onClick={() => setStep(1)}>
          <Libs.ArrowLeft className="h-4 w-4" />
          {tCommon('back')}
        </Atoms.Button>
        <Atoms.Button
          id="backup-recovery-phrase-validate-btn"
          size="lg"
          onClick={handleValidate}
          disabled={!isComplete}
        >
          <Libs.Check className="h-4 w-4" />
          {t('validate')}
        </Atoms.Button>
      </Atoms.DialogFooter>
    </>
  );
}

function RecoveryStep3({ handleClose }: { handleClose: () => void }) {
  const t = useTranslations('onboarding.backupPhrase');
  const tCommon = useTranslations('common');

  return (
    <>
      <Atoms.DialogHeader>
        <Atoms.DialogTitle>{t('completeTitle')}</Atoms.DialogTitle>
        <Atoms.DialogDescription>{t('completeSubtitle')}</Atoms.DialogDescription>
      </Atoms.DialogHeader>

      <Atoms.Container className="flex w-full items-center justify-center rounded-md bg-card p-12">
        <Image src="/images/check.webp" alt={t('completeTitle')} width={180} height={180} className="h-48 w-48" />
      </Atoms.Container>

      <Atoms.DialogFooter className="flex-col gap-3">
        <Atoms.DialogClose asChild>
          <Atoms.Button id="backup-recovery-phrase-finish-btn" size="lg" className="w-full" onClick={handleClose}>
            <Libs.ArrowRight className="h-4 w-4" />
            {tCommon('finish')}
          </Atoms.Button>
        </Atoms.DialogClose>
        <Atoms.DialogClose asChild>
          <Atoms.Button variant="outline" size="lg" className="w-full" onClick={handleClose}>
            {tCommon('cancel')}
          </Atoms.Button>
        </Atoms.DialogClose>
      </Atoms.DialogFooter>
    </>
  );
}
