import { Env } from '@/libs/env/env';

export const TESTNET = Env.NEXT_PUBLIC_TESTNET;
export const PKARR_RELAYS = Env.NEXT_PUBLIC_PKARR_RELAYS;
export const HOMESERVER = Env.NEXT_PUBLIC_HOMESERVER;
export const DEFAULT_HTTP_RELAY = Env.NEXT_PUBLIC_DEFAULT_HTTP_RELAY;
export const EXCHANGE_RATE_API = Env.NEXT_PUBLIC_EXCHANGE_RATE_API;
export const HOMEGATE_URL = Env.NEXT_PUBLIC_HOMEGATE_URL;
