'use client';
import { AuthController } from '@/controllers/auth/auth';
import { getRetryAfter, hasHttpStatus, isAppError, isAuthError, isRetryable } from '@/libs/error/error.utils';
import { HttpStatusCode } from '@/libs/http/http.types';
import { toast } from '@/molecules/Toaster/toast';
import { useOnboardingStore } from '@/stores/onboarding/onboarding.store';
import type { UseInviteCodeSignUpResult } from './useInviteCodeSignUp.types';

const SIGN_UP_MAX_ATTEMPTS = 4;
const SIGN_UP_RETRY_BASE_DELAY_MS = 500;
const SIGN_UP_RETRY_MAX_DELAY_MS = 5000;

/**
 * Attempts signup with an invite code using the existing keypair from the onboarding store.
 * There is no "validate only" API; the homeserver validates during signup.
 *
 * Expects secrets to already exist in the onboarding store (generated by ProfileController.generateSecrets
 * during the pubky step). The auth store is updated only when AuthController.signUp succeeds.
 *
 * On success the keys in the onboarding store become the user's real keys.
 * On failure it keeps the secrets whenever the homeserver may already hold an account for them (any
 * retryable failure, a 409 conflict, or anything after such a failure) and clears them otherwise.
 * In both failure paths it shows a toast and throws so the caller can keep the user on the form.
 *
 * @example
 * const { validateAndSignUp } = useInviteCodeSignUp();
 * const onContinue = async () => {
 *   const inviteCode = useOnboardingStore.getState().inviteCode;
 *   await validateAndSignUp(inviteCode);
 *   router.push(ONBOARDING_ROUTES.BACKUP);
 * };
 */
export function useInviteCodeSignUp(): UseInviteCodeSignUpResult {
  const getRetryDelayMs = (attempt: number, retryAfterSeconds?: number): number => {
    if (typeof retryAfterSeconds === 'number' && Number.isFinite(retryAfterSeconds) && retryAfterSeconds > 0) {
      return Math.min(retryAfterSeconds * 1000, SIGN_UP_RETRY_MAX_DELAY_MS);
    }

    return Math.min(SIGN_UP_RETRY_BASE_DELAY_MS * 2 ** attempt, SIGN_UP_RETRY_MAX_DELAY_MS);
  };

  const sleep = async (ms: number): Promise<void> => {
    await new Promise((resolve) => setTimeout(resolve, ms));
  };

  async function validateAndSignUp(inviteCode: string) {
    const secretKey = useOnboardingStore.getState().selectSecretKey();

    let lastError: unknown;
    // The sign-up registers the account (spending the invite code on this keypair) before it publishes
    // the PKDNS record, so a retryable failure may have landed after the account existed, and a 409
    // means it did. Once that is possible the keypair must survive every later failure of this call:
    // clearing it would orphan the registered account, and a fresh keypair could never reuse the code.
    let keypairMayBeRegistered = false;

    for (let attempt = 0; attempt < SIGN_UP_MAX_ATTEMPTS; attempt += 1) {
      let description = 'Could not sign up. Try again.';

      try {
        await AuthController.signUp({ secretKey, signupToken: inviteCode });
        return;
      } catch (error) {
        lastError = error;

        const retryable = isAppError(error) && isRetryable(error);
        const conflict = hasHttpStatus(error, HttpStatusCode.CONFLICT);
        keypairMayBeRegistered ||= retryable || conflict;

        if (retryable && attempt < SIGN_UP_MAX_ATTEMPTS - 1) {
          const retryAfter = getRetryAfter(error);
          await sleep(getRetryDelayMs(attempt, retryAfter));
          continue;
        }

        if (!keypairMayBeRegistered) {
          useOnboardingStore.getState().clearSecrets();
        }

        if (conflict) {
          description = 'Your pubky is already registered. Try again to finish signing in.';
        } else if (isAppError(error)) {
          if (isAuthError(error)) {
            description = 'Invite code is invalid or expired.';
          } else if (error.message) {
            description = error.message;
          }
        }

        toast({
          variant: 'error',
          description,
        });
        throw error;
      }
    }

    throw lastError ?? new Error('[useInviteCodeSignUp] Sign-up failed after retries');
  }

  return { validateAndSignUp };
}
