'use client';
import { AuthController } from '@/controllers/auth/auth';
import { getRetryAfter, isAppError, isAuthError, isRetryable } from '@/libs/error/error.utils';
import { toast } from '@/molecules/Toaster/toast';
import { useOnboardingStore } from '@/stores/onboarding/onboarding.store';
import type { UseInviteCodeSignUpResult } from './useInviteCodeSignUp.types';

const SIGN_UP_MAX_ATTEMPTS = 4;
const SIGN_UP_RETRY_BASE_DELAY_MS = 500;
const SIGN_UP_RETRY_MAX_DELAY_MS = 5000;

/**
 * Attempts signup with an invite code using the existing keypair from the onboarding store.
 * There is no "validate only" API; the homeserver validates during signup.
 *
 * Expects secrets to already exist in the onboarding store (generated by ProfileController.generateSecrets
 * during the pubky step). The auth store is updated only when AuthController.signUp succeeds.
 *
 * On success the keys in the onboarding store become the user's real keys.
 * Keeps the original onboarding secrets after any failure so a consumed invite remains recoverable.
 * In both failure paths it shows a toast and throws so the caller can keep the user on the form.
 *
 * @example
 * const { validateAndSignUp } = useInviteCodeSignUp();
 * const onContinue = async () => {
 *   const inviteCode = useOnboardingStore.getState().inviteCode;
 *   await validateAndSignUp(inviteCode);
 *   router.push(ONBOARDING_ROUTES.BACKUP);
 * };
 */
export function useInviteCodeSignUp(): UseInviteCodeSignUpResult {
  const getRetryDelayMs = (attempt: number, retryAfterSeconds?: number): number => {
    if (typeof retryAfterSeconds === 'number' && Number.isFinite(retryAfterSeconds) && retryAfterSeconds > 0) {
      return Math.min(retryAfterSeconds * 1000, SIGN_UP_RETRY_MAX_DELAY_MS);
    }

    return Math.min(SIGN_UP_RETRY_BASE_DELAY_MS * 2 ** attempt, SIGN_UP_RETRY_MAX_DELAY_MS);
  };

  const sleep = async (ms: number): Promise<void> => {
    await new Promise((resolve) => setTimeout(resolve, ms));
  };

  async function validateAndSignUp(inviteCode: string) {
    const secretKey = useOnboardingStore.getState().selectSecretKey();

    let lastError: unknown;

    for (let attempt = 0; attempt < SIGN_UP_MAX_ATTEMPTS; attempt += 1) {
      let description = 'Could not sign up. Try again.';

      try {
        await AuthController.signUp({ secretKey, signupToken: inviteCode });
        return;
      } catch (error) {
        lastError = error;

        const canRetry = isAppError(error) && isRetryable(error) && attempt < SIGN_UP_MAX_ATTEMPTS - 1;
        if (canRetry) {
          const retryAfter = getRetryAfter(error);
          await sleep(getRetryDelayMs(attempt, retryAfter));
          continue;
        }

        // Retain the original keys: account creation may have succeeded before the response was lost.

        if (isAppError(error)) {
          if (isAuthError(error)) {
            description = useOnboardingStore.getState().signupAttempt
              ? 'Could not finish signing in. Your recovery keys are still saved. Try again.'
              : 'Invite code is invalid or expired.';
          } else if (error.message) {
            description = error.message;
          }
        }

        toast({
          variant: 'error',
          description,
        });
        throw error;
      }
    }

    throw lastError;
  }

  return { validateAndSignUp };
}
