name: e2e-test
env:
  pubky_stack_ref: 'staging'
  platforms: 'linux/amd64'
  registry: 'europe-west6-docker.pkg.dev/infra-464608/synonym-private-repo'

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

jobs:
  rebuild_images:
    name: Getting images to rebuild
    runs-on: ubuntu-latest
    outputs:
      homeserver-testnet_tag: ${{ steps.set_tag.outputs.homeserver-testnet_tag }}
      pubky-nexus_tag: ${{ steps.set_tag.outputs.pubky-nexus_tag }}
    strategy:
      matrix:
        include:
          - app: "pubky-nexus"
            submodule_dir: "pubky-stack/pubky-nexus/"
            image: "pubky-nexus"

          - app: "homeserver"
            submodule_dir: "pubky-stack/pubky-core/"
            image: "homeserver-testnet"

    steps:
      - name: Checkout pubky-stack
        uses: actions/checkout@v4
        with:
          repository: pubky/pubky-stack
          ref: ${{ env.pubky_stack_ref }}
          path: pubky-stack
          submodules: true
          token: ${{ secrets.READ_REPOS }}
          # cannot use ssh-key (deploy key) for private submodules due to the
          # limitation where only a single key can be used per repo checkout
          # see https://github.com/actions/checkout/issues/183

      - name: Set HEAD commit hash
        id: sha_tag
        uses: pubky/ci-workflows/.github/actions/docker/get_head_commit_hash@main
        with:
          path: ${{ matrix.submodule_dir }}

      - name: Set Current Tag as Output
        id: set_tag
        run: |
          echo ${{ matrix.image }}_tag=${{ steps.sha_tag.outputs.hash }} >> $GITHUB_OUTPUT

      - name: Login to registry
        uses: pubky/ci-workflows/.github/actions/docker/registry_login@main
        with:
          registry: ${{ env.registry }}
          gcp_service_account_key: ${{ secrets.GCR_JSON_KEY }}

      - name: Check if image needs to be rebuild
        uses: pubky/ci-workflows/.github/actions/docker/check_if_image_exists@main
        id: check_image
        with:
          image: ${{ env.registry }}/${{ matrix.image }}
          tag: ${{ steps.sha_tag.outputs.hash }}
          arch: ${{ env.platforms }}

      - name: Rebuild the images if needed
        uses: pubky/ci-workflows/.github/actions/docker/build_and_push@main
        with:
          registry: ${{ env.registry }}
          image: ${{ matrix.image }}
          context: ${{ matrix.submodule_dir }}
          platforms: ${{ env.platforms }}
        if: ${{ steps.check_image.outputs.exists != 'true' }}

  set_vars_pubky_app:
    name: Set vars for Pubky App
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set_vars.outputs.env }}
      platforms: ${{ steps.set_vars.outputs.platforms }}
    steps:
      - name: Set Vars
        id: set_vars
        run: |
          echo platforms=${{ env.platforms }} >> $GITHUB_OUTPUT

  rebuild_pubky_app:
    needs: [ set_vars_pubky_app ]
    uses: ./.github/workflows/build-docker-image.yml
    with:
      platforms: ${{ needs.set_vars_pubky_app.outputs.platforms }}
    secrets: inherit

  e2e-test:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [rebuild_images, rebuild_pubky_app]
    env:
      HOMESERVER_TAG: ${{ needs.rebuild_images.outputs.homeserver-testnet_tag }}
      PUBKY_APP_TAG: ${{ needs.rebuild_pubky_app.outputs.image_tag }}
      PUBKY_NEXUS_TAG: ${{ needs.rebuild_images.outputs.pubky-nexus_tag }}
    permissions:
      contents: read
      statuses: write
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
        spec: ["contacts.cy.ts", "feed.cy.ts", "notifications.cy.ts", "onboarding.cy.ts", "posts.cy.ts", "profile.cy.ts", "search.cy.ts", "settings.cy.ts", "collections.cy.ts"]

    steps:
      - name: Validate envs from rebuild_images job
        run: |
          if [ -z "${{ env.HOMESERVER_TAG }}" ]; then
            echo "Error: env HOMESERVER_TAG is empty!"
            exit 1
          fi

          if [ -z "${{ env.PUBKY_APP_TAG }}" ]; then
            echo "Error: env PUBKY_APP_TAG is empty!"
            exit 1
          fi

          if [ -z "${{ env.PUBKY_NEXUS_TAG }}" ]; then
            echo "Error: env PUBKY_NEXUS_TAG is empty!"
            exit 1
          fi

      - name: Checkout pubky-stack
        uses: actions/checkout@v4
        with:
          repository: pubky/pubky-stack
          ref: ${{ env.pubky_stack_ref }}
          path: pubky-stack
          submodules: true
          token: ${{ secrets.READ_REPOS }}
          # cannot use ssh-key (deploy key) for private submodules due to the
          # limitation where only a single key can be used per repo checkout
          # see https://github.com/actions/checkout/issues/183

      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: pubky-app

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'pubky-app/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'pubky-app/package-lock.json'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            pubky-app/node_modules
            pubky-app/.next/cache
          key: ${{ runner.os }}-node-${{ hashFiles('pubky-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Cypress dependencies
        working-directory: pubky-app
        run: npm ci

      - name: Login to registry
        uses: pubky/ci-workflows/.github/actions/docker/registry_login@main
        with:
          registry: ${{ env.registry }}
          gcp_service_account_key: ${{ secrets.GCR_JSON_KEY }}

      - name: Modify neo4j.env
        working-directory: pubky-stack/docker
        run: |
          sed -i 's/NEO4J_server_memory_pagecache_size=2G/NEO4J_server_memory_pagecache_size=1G/' neo4j.env
          sed -i 's/NEO4J_server_memory_heap_initial__size=4G/NEO4J_server_memory_heap_initial__size=1G/' neo4j.env
          sed -i 's/NEO4J_server_memory_heap_max__size=8G/NEO4J_server_memory_heap_max__size=2G/' neo4j.env

      - name: Increase watcher sleep in Nexus config
        working-directory: pubky-stack/docker
        run: |
          sed -i 's/watcher_sleep = 100/watcher_sleep = 500/' pubky-nexus-config-testnet.toml

      - name: Prepare pubky-stack .env
        working-directory: pubky-stack/docker
        run: |
          cp .env-sample .env

      - name: Run pubky-stack
        working-directory: pubky-stack/docker
        run: docker compose up -d --no-build homeserver nexusd nexus-neo4j nexus-redis pubky-app postgres
        env:
          REGISTRY: ${{ env.registry }}

      - name: Wait for dockerised pubky-stack to start
        run: |
          PORT=8080
          MAX_WAIT=300     # Maximum wait time in seconds (5 minutes)
          WAIT_INTERVAL=5  # Interval between checks in seconds
          ELAPSED=0

          while ! curl -s http://localhost:$PORT; do
            if [ $ELAPSED -ge $MAX_WAIT ]; then
              echo "Service did not start within 5 minutes."
              exit 1
            fi
            echo "Waiting for service on port $PORT to be ready... ($ELAPSED seconds elapsed)"
            sleep $WAIT_INTERVAL
            ELAPSED=$((ELAPSED + WAIT_INTERVAL))
          done

          echo "Service is ready."

      - name: Run e2e tests - Desktop (${{ matrix.browser }}) - Spec (${{matrix.spec}})
        id: test-desktop
        uses: cypress-io/github-action@v6
        env:
          DEBUG: '@cypress/github-action'
        with:
          working-directory: pubky-app/cypress
          config-file: cypress.config.ts
          spec: e2e/${{ matrix.spec }}
          browser: ${{ matrix.browser }}
          headed: false
          summary-title: ${{ matrix.browser }} - Desktop
          install: false
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180

      - name: Upload screenshots - ${{ matrix.browser }} - Desktop
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}-${{ matrix.spec }}-desktop
          path: pubky-app/cypress/screenshots
          if-no-files-found: ignore

      - name: Upload video for ${{ matrix.spec }} test - ${{ matrix.browser }} - Desktop
        if: always() && steps.test-desktop.outcome == 'failure'
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: video-${{ matrix.browser }}-${{ matrix.spec }}-desktop-onboarding
          path: pubky-app/cypress/videos/${{ matrix.spec }}.mp4
          if-no-files-found: ignore

      # TODO: Skipped due to bug https://github.com/pubky/pubky-app/issues/372
      # - name: Run e2e tests - Mobile (${{ matrix.browser }})
      #   id: test-mobile
      #   uses: cypress-io/github-action@v6
      #   env:
      #     DEBUG: '@cypress/github-action'
      #   with:
      #     working-directory: pubky-app/cypress
      #     config-file: cypress.config.mobile.ts
      #     spec: e2e/**/*.cy.ts
      #     browser: ${{ matrix.browser }}
      #     headed: false
      #     summary-title: ${{ matrix.browser }} - Mobile
      #     install: false
      #     # no need to start the server, it's already running
      #     wait-on: 'http://localhost:3000'
      #     wait-on-timeout: 180

      - name: Upload screenshots - ${{ matrix.browser }} - Mobile
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}-${{ matrix.spec }}-mobile
          path: pubky-app/cypress/screenshots/mobile
          if-no-files-found: ignore

      - name: Upload video for ${{ matrix.spec }} test - ${{ matrix.browser }} - Mobile
        if: always() && steps.test-mobile.outcome == 'failure'
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: video-${{ matrix.browser }}-${{ matrix.spec }}-mobile-onboarding
          path: pubky-app/cypress/videos/mobile/${{ matrix.spec }}.mp4
          if-no-files-found: ignore

      - name: Upload cypress.log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: cypress-log-${{ matrix.browser }}-${{ matrix.spec }}
          path: pubky-app/cypress/cypress.log
          if-no-files-found: ignore

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
